#pragma once

#include <string>
#include <unordered_map>

namespace LangStorage
{
	inline std::unordered_map<std::string, std::string> language
	{
		{ "afar", "aar" },
		{ "abkhaz", "abk" },
		{ "achinese", "ace" },
		{ "acoli", "ach" },
		{ "adangme", "ada" },
		{ "adygei", "ady" },
		{ "afroasiatic (other)", "afa" },
		{ "afrikaans", "afr" },
		{ "akan", "aka" },
		{ "akkadian", "akk" },
		{ "albanian", "alb" },
		{ "aleut", "ale" },
		{ "algonquian (other)", "alg" },
		{ "altai", "alt" },
		{ "amharic", "amh" },
		{ "english, old (ca. 450-1100)", "ang" },
		{ "apache languages", "apa" },
		{ "arabic", "ara" },
		{ "aramaic", "arc" },
		{ "aragonese", "arg" },
		{ "armenian", "arm" },
		{ "mapuche", "arn" },
		{ "arapaho", "arp" },
		{ "artificial (other)", "art" },
		{ "arawak", "arw" },
		{ "american sign language", "ase" },
		{ "assamese", "asm" },
		{ "asturian", "ast" },
		{ "athapascan (other)", "ath" },
		{ "australian languages", "aus" },
		{ "avaric", "ava" },
		{ "avestan", "ave" },
		{ "awadhi ", "awa" },
		{ "aymara", "aym" },
		{ "azerbaijani", "aze" },
		{ "bamileke languages", "bai" },
		{ "bashkir", "bak" },
		{ "baluchi", "bal" },
		{ "bambara", "bam" },
		{ "balinese", "ban" },
		{ "basque", "baq" },
		{ "basa", "bas" },
		{ "baltic (other)", "bat" },
		{ "belarusian", "bel" },
		{ "bemba", "bem" },
		{ "bengali", "ben" },
		{ "berber (other)", "ber" },
		{ "bhojpuri", "bho" },
		{ "bikol", "bik" },
		{ "edo", "bin" },
		{ "bislama", "bis" },
		{ "siksika", "bla" },
		{ "bantu (other)", "bnt" },
		{ "bosnian", "bos" },
		{ "braj", "bra" },
		{ "breton", "bre" },
		{ "batak", "btk" },
		{ "buriat", "bua" },
		{ "bugis", "bug" },
		{ "bulgarian", "bul" },
		{ "burmese", "bur" },
		{ "central american indian (other)", "cai" },
		{ "khmer", "cam" },
		{ "carib", "car" },
		{ "catalan", "cat" },
		{ "caucasian (other)", "cau" },
		{ "cebuano", "ceb" },
		{ "celtic (other)", "cel" },
		{ "chechen", "che" },
		{ "chagatai", "chg" },
		{ "chinese", "chi" },
		{ "chuukese", "chk" },
		{ "mari", "chm" },
		{ "chinook jargon", "chn" },
		{ "choctaw", "cho" },
		{ "cherokee", "chr" },
		{ "church slavic", "chu" },
		{ "chuvash", "chv" },
		{ "cheyenne", "chy" },
		{ "chamic languages", "cmc" },
		{ "mandarin", "cmn" },
		{ "coptic", "cop" },
		{ "cornish", "cor" },
		{ "corsican", "cos" },
		{ "creoles and pidgins, english-based (other)", "cpe" },
		{ "creoles and pidgins, french-based (other)", "cpf" },
		{ "creoles and pidgins, portuguese-based (other)", "cpp" },
		{ "cree", "cre" },
		{ "crimean tatar", "crh" },
		{ "creoles and pidgins (other)", "crp" },
		{ "cushitic (other)", "cus" },
		{ "czech", "cze" },
		{ "dakota", "dak" },
		{ "danish", "dan" },
		{ "dargwa", "dar" },
		{ "dayak", "day" },
		{ "delaware", "del" },
		{ "dinka", "din" },
		{ "maldivian", "div" },
		{ "dogri", "doi" },
		{ "dravidian (other)", "dra" },
		{ "duala", "dua" },
		{ "dutch, middle (ca. 1050-1350)", "dum" },
		{ "dutch", "dut" },
		{ "dyula", "dyu" },
		{ "dzongkha", "dzo" },
		{ "efik", "efi" },
		{ "egyptian", "egy" },
		{ "ekajuk", "eka" },
		{ "elamite", "elx" },
		{ "english", "eng" },
		{ "english, middle (1100-1500)", "enm" },
		{ "esperanto", "epo" },
		{ "eskimo languages", "esk" },
		{ "esperanto", "esp" },
		{ "estonian", "est" },
		{ "ethiopic", "eth" },
		{ "ewe", "ewe" },
		{ "ewondo", "ewo" },
		{ "fang", "fan" },
		{ "faroese", "fao" },
		{ "faroese", "far" },
		{ "fanti", "fat" },
		{ "fijian", "fij" },
		{ "filipino", "fil" },
		{ "finnish", "fin" },
		{ "finno-ugrian (other)", "fiu" },
		{ "fon", "fon" },
		{ "french", "fre" },
		{ "frisian", "fri" },
		{ "french, middle (ca. 1300-1600)", "frm" },
		{ "french, old (ca. 842-1300)", "fro" },
		{ "east frisian", "frs" },
		{ "frisian", "fry" },
		{ "fula", "ful" },
		{ "friulian", "fur" },
		{ "ga", "gaa" },
		{ "scottish gaelix", "gae" },
		{ "galician", "gag" },
		{ "oromo", "gal" },
		{ "gayo", "gay" },
		{ "gbaya", "gba" },
		{ "germanic (other)", "gem" },
		{ "georgian", "geo" },
		{ "german", "ger" },
		{ "ethiopic", "gez" },
		{ "gilbertese", "gil" },
		{ "scottish gaelic", "gla" },
		{ "irish", "gle" },
		{ "galician ", "glg" },
		{ "manx", "glv" },
		{ "german, middle high (ca. 1050-1500)", "gmh" },
		{ "old high german", "goh" },
		{ "gondi", "gon" },
		{ "gorontalo", "gor" },
		{ "gothic", "got" },
		{ "grebo", "grb" },
		{ "ancient greek", "grc" },
		{ "greek", "gre" },
		{ "guarani", "grn" },
		{ "swiss german", "gsw" },
		{ "guarani", "gua" },
		{ "gujarati", "guj" },
		{ "gullah", "gul" },
		{ "haitian french creole", "hat" },
		{ "hausa", "hau" },
		{ "hawaiian", "haw" },
		{ "serbo-croatian", "hbs" },
		{ "hebrew", "heb" },
		{ "herero", "her" },
		{ "hiligaynon", "hil" },
		{ "himachali", "him" },
		{ "hindi", "hin" },
		{ "hmong", "hmn" },
		{ "hiri motu", "hmo" },
		{ "croatian", "hrv" },
		{ "hungarian", "hun" },
		{ "iban", "iba" },
		{ "igbo", "ibo" },
		{ "icelandic", "ice" },
		{ "ido", "ido" },
		{ "ijo", "ijo" },
		{ "inuktitut", "iku" },
		{ "iloko", "ilo" },
		{ "interlingua (international auxiliary language association)", "ina" },
		{ "indic (other)", "inc" },
		{ "indonesian", "ind" },
		{ "indo-european (other)", "ine" },
		{ "ingush", "inh" },
		{ "interlingua (international auxiliary language association)", "int" },
		{ "inupiaq", "ipk" },
		{ "iranian (other)", "ira" },
		{ "irish", "iri" },
		{ "iroquoian (other)", "iro" },
		{ "italian", "ita" },
		{ "javanese", "jav" },
		{ "japanese", "jpn" },
		{ "judeo-persian", "jpr" },
		{ "judeo-arabic", "jrb" },
		{ "kara-kalpak", "kaa" },
		{ "kabyle", "kab" },
		{ "kachin", "kac" },
		{ "kalatdlisut", "kal" },
		{ "kamba", "kam" },
		{ "kannada", "kan" },
		{ "karen languages", "kar" },
		{ "kashmiri", "kas" },
		{ "kanuri", "kau" },
		{ "kawi", "kaw" },
		{ "kazakh", "kaz" },
		{ "kabardian", "kbd" },
		{ "khasi", "kha" },
		{ "khoisan (other)", "khi" },
		{ "khmer", "khm" },
		{ "khotanese", "kho" },
		{ "kikuyu", "kik" },
		{ "kinyarwanda", "kin" },
		{ "kyrgyz", "kir" },
		{ "kimbundu", "kmb" },
		{ "konkani ", "kok" },
		{ "komi", "kom" },
		{ "kongo", "kon" },
		{ "korean", "kor" },
		{ "kusaie", "kos" },
		{ "kpelle", "kpe" },
		{ "karachay-balkar", "krc" },
		{ "karelian", "krl" },
		{ "kru (other)", "kro" },
		{ "kurukh", "kru" },
		{ "kuanyama", "kua" },
		{ "kumyk", "kum" },
		{ "kurdish", "kur" },
		{ "ladino", "lad" },
		{ "lahnda", "lah" },
		{ "lamba (zambia and congo)", "lam" },
		{ "occitan (post 1500)", "lan" },
		{ "lao", "lao" },
		{ "sami", "lap" },
		{ "latin", "lat" },
		{ "latvian", "lav" },
		{ "lezgian", "lez" },
		{ "lingala", "lin" },
		{ "lithuanian", "lit" },
		{ "mongo-nkundu", "lol" },
		{ "lozi", "loz" },
		{ "luxembourgish", "ltz" },
		{ "luba-lulua", "lua" },
		{ "luba-katanga", "lub" },
		{ "ganda", "lug" },
		{ "lunda", "lun" },
		{ "luo (kenya and tanzania)", "luo" },
		{ "lushai", "lus" },
		{ "macedonian", "mac" },
		{ "madurese", "mad" },
		{ "magahi", "mag" },
		{ "marshallese", "mah" },
		{ "maithili", "mai" },
		{ "makasar", "mak" },
		{ "malayalam", "mal" },
		{ "mandingo", "man" },
		{ "maori", "mao" },
		{ "austronesian (other)", "map" },
		{ "marathi", "mar" },
		{ "masai", "mas" },
		{ "malay", "may" },
		{ "moksha", "mdf" },
		{ "mende", "men" },
		{ "micmac", "mic" },
		{ "minangkabau", "min" },
		{ "miscellaneous languages", "mis" },
		{ "mon-khmer (other)", "mkh" },
		{ "malagasy", "mla" },
		{ "malagasy", "mlg" },
		{ "maltese", "mlt" },
		{ "manchu", "mnc" },
		{ "manipuri", "mni" },
		{ "manobo languages", "mno" },
		{ "mohawk", "moh" },
		{ "moldavian", "mol" },
		{ "mongolian", "mon" },
		{ "moore", "mos" },
		{ "multiple languages", "mul" },
		{ "munda (other)", "mun" },
		{ "creek", "mus" },
		{ "mirandese", "mwl" },
		{ "marwari", "mwr" },
		{ "mayan languages", "myn" },
		{ "erzya", "myv" },
		{ "nahuatl", "nah" },
		{ "north american indian (other)", "nai" },
		{ "nauru", "nau" },
		{ "navajo", "nav" },
		{ "ndebele (south africa)", "nbl" },
		{ "ndebele (zimbabwe)", "nde" },
		{ "ndonga", "ndo" },
		{ "low german", "nds" },
		{ "nepali", "nep" },
		{ "newari", "new" },
		{ "niger-kordofanian (other)", "nic" },
		{ "niuean", "niu" },
		{ "norwegian (nynorsk)", "nno" },
		{ "norwegian (bokmal)", "nob" },
		{ "nogai", "nog" },
		{ "old norse", "non" },
		{ "norwegian", "nor" },
		{ "northern sotho", "nso" },
		{ "nubian languages", "nub" },
		{ "nyanja", "nya" },
		{ "nyankole", "nyn" },
		{ "nyoro", "nyo" },
		{ "nzima", "nzi" },
		{ "occitan (post 1500)", "oci" },
		{ "ojibwa", "oji" },
		{ "oriya", "ori" },
		{ "oromo", "orm" },
		{ "osage", "osa" },
		{ "ossetic", "oss" },
		{ "turkish, ottoman", "ota" },
		{ "otomian languages", "oto" },
		{ "papuan (other)", "paa" },
		{ "pangasinan", "pag" },
		{ "pahlavi", "pal" },
		{ "pampanga", "pam" },
		{ "panjabi", "pan" },
		{ "papiamento", "pap" },
		{ "palauan", "pau" },
		{ "old persian (ca. 600-400 b.c.)", "peo" },
		{ "persian", "per" },
		{ "philippine (other)", "phi" },
		{ "pali", "pli" },
		{ "polish", "pol" },
		{ "ponape", "pon" },
		{ "portuguese", "por" },
		{ "prakrit languages", "pra" },
		{ "provencal (to 1500)", "pro" },
		{ "pushto", "pus" },
		{ "quechua", "que" },
		{ "rajasthani", "raj" },
		{ "rarotongan", "rar" },
		{ "romance (other)", "roa" },
		{ "raeto-romance", "roh" },
		{ "romani", "rom" },
		{ "romanian", "rum" },
		{ "rundi", "run" },
		{ "russian", "rus" },
		{ "sango (ubangi creole)", "sag" },
		{ "yakut", "sah" },
		{ "south american indian (other)", "sai" },
		{ "salishan languages", "sal" },
		{ "samaritan aramaic", "sam" },
		{ "sanskrit", "san" },
		{ "samoan", "sao" },
		{ "sasak", "sas" },
		{ "santali", "sat" },
		{ "serbian", "scc" },
		{ "scots", "sco" },
		{ "croatian", "scr" },
		{ "selkup", "sel" },
		{ "semitic (other)", "sem" },
		{ "shan", "shn" },
		{ "shona", "sho" },
		{ "sidamo", "sid" },
		{ "sinhalese", "sin" },
		{ "siouan (other)", "sio" },
		{ "sino-tibetan (other)", "sit" },
		{ "slavic (other)", "sla" },
		{ "slovak", "slo" },
		{ "slovenian", "slv" },
		{ "northern sami", "sme" },
		{ "sami", "smi" },
		{ "samoan", "smo" },
		{ "shona", "sna" },
		{ "sindhi", "snd" },
		{ "sinhalese", "snh" },
		{ "soninke", "snk" },
		{ "sogdian", "sog" },
		{ "somali", "som" },
		{ "songhai", "son" },
		{ "sotho", "sot" },
		{ "spanish", "spa" },
		{ "sardinian", "srd" },
		{ "sranan", "srn" },
		{ "serbian", "srp" },
		{ "serer", "srr" },
		{ "nilo-saharan (other)", "ssa" },
		{ "sotho", "sso" },
		{ "swazi ", "ssw" },
		{ "sukuma", "suk" },
		{ "sundanese", "sun" },
		{ "susu", "sus" },
		{ "sumerian", "sux" },
		{ "swahili", "swa" },
		{ "swedish", "swe" },
		{ "swazi", "swz" },
		{ "syriac", "syc" },
		{ "syriac, modern", "syr" },
		{ "tagalog", "tag" },
		{ "tahitian", "tah" },
		{ "tai", "tai" },
		{ "tajik", "taj" },
		{ "tamil", "tam" },
		{ "tatar", "tar" },
		{ "tatar", "tat" },
		{ "telugu", "tel" },
		{ "temne", "tem" },
		{ "terena", "ter" },
		{ "tetum", "tet" },
		{ "tajik ", "tgk" },
		{ "tagalog", "tgl" },
		{ "thai", "tha" },
		{ "tibetan", "tib" },
		{ "tigre", "tig" },
		{ "tigrinya", "tir" },
		{ "tiv", "tiv" },
		{ "tokelauan", "tkl" },
		{ "tlingit", "tli" },
		{ "tamashek", "tmh" },
		{ "tonga (nyasa)", "tog" },
		{ "tongan", "ton" },
		{ "tok pisin", "tpi" },
		{ "tsimshian", "tsi" },
		{ "tswana", "tsn" },
		{ "tsonga", "tso" },
		{ "tswana", "tsw" },
		{ "turkmen", "tuk" },
		{ "tumbuka", "tum" },
		{ "turkish", "tur" },
		{ "altaic (other)", "tut" },
		{ "tuvaluan", "tvl" },
		{ "twi", "twi" },
		{ "tuvinian", "tyv" },
		{ "udmurt ", "udm" },
		{ "ugaritic", "uga" },
		{ "uighur", "uig" },
		{ "ukrainian", "ukr" },
		{ "umbundu", "umb" },
		{ "undetermined", "und" },
		{ "urdu", "urd" },
		{ "uzbek", "uzb" },
		{ "vai", "vai" },
		{ "venda", "ven" },
		{ "vietnamese", "vie" },
		{ "flemish", "vls" },
		{ "wakashan languages", "wak" },
		{ "wolayta", "wal" },
		{ "waray", "war" },
		{ "welsh", "wel" },
		{ "sorbian (other)", "wen" },
		{ "wolof ", "wol" },
		{ "oirat", "xal" },
		{ "xhosa", "xho" },
		{ "yao (africa)", "yao" },
		{ "yapese", "yap" },
		{ "yiddish", "yid" },
		{ "yoruba", "yor" },
		{ "yupik languages", "ypk" },
		{ "cantonese", "yue" },
		{ "zapotec", "zap" },
		{ "zande languages", "znd" },
		{ "zulu", "zul" },
		{ "zuni", "zun" },
		{ "zaza", "zza" }
	};
}