#pragma once

#include <string>
#include <unordered_map>

namespace LangStorage
{
	inline std::unordered_map<std::string, std::string> language
	{
		{ "Afar", "aar" },
		{ "Abkhaz", "abk" },
		{ "Achinese", "ace" },
		{ "Acoli", "ach" },
		{ "Adangme", "ada" },
		{ "Adygei", "ady" },
		{ "Afroasiatic (Other)", "afa" },
		{ "Afrikaans", "afr" },
		{ "Akan", "aka" },
		{ "Akkadian", "akk" },
		{ "Albanian", "alb" },
		{ "Aleut", "ale" },
		{ "Algonquian (Other)", "alg" },
		{ "Altai", "alt" },
		{ "Amharic", "amh" },
		{ "English, Old (ca. 450-1100)", "ang" },
		{ "Apache languages", "apa" },
		{ "Arabic", "ara" },
		{ "Aramaic", "arc" },
		{ "Aragonese", "arg" },
		{ "Armenian", "arm" },
		{ "Mapuche", "arn" },
		{ "Arapaho", "arp" },
		{ "Artificial (Other)", "art" },
		{ "Arawak", "arw" },
		{ "American Sign Language", "ase" },
		{ "Assamese", "asm" },
		{ "Asturian", "ast" },
		{ "Athapascan (Other)", "ath" },
		{ "Australian languages", "aus" },
		{ "Avaric", "ava" },
		{ "Avestan", "ave" },
		{ "Awadhi ", "awa" },
		{ "Aymara", "aym" },
		{ "Azerbaijani", "aze" },
		{ "Bamileke languages", "bai" },
		{ "Bashkir", "bak" },
		{ "Baluchi", "bal" },
		{ "Bambara", "bam" },
		{ "Balinese", "ban" },
		{ "Basque", "baq" },
		{ "Basa", "bas" },
		{ "Baltic (Other)", "bat" },
		{ "Belarusian", "bel" },
		{ "Bemba", "bem" },
		{ "Bengali", "ben" },
		{ "Berber (Other)", "ber" },
		{ "Bhojpuri", "bho" },
		{ "Bikol", "bik" },
		{ "Edo", "bin" },
		{ "Bislama", "bis" },
		{ "Siksika", "bla" },
		{ "Bantu (Other)", "bnt" },
		{ "Bosnian", "bos" },
		{ "Braj", "bra" },
		{ "Breton", "bre" },
		{ "Batak", "btk" },
		{ "Buriat", "bua" },
		{ "Bugis", "bug" },
		{ "Bulgarian", "bul" },
		{ "Burmese", "bur" },
		{ "Central American Indian (Other)", "cai" },
		{ "Khmer", "cam" },
		{ "Carib", "car" },
		{ "Catalan", "cat" },
		{ "Caucasian (Other)", "cau" },
		{ "Cebuano", "ceb" },
		{ "Celtic (Other)", "cel" },
		{ "Chechen", "che" },
		{ "Chagatai", "chg" },
		{ "Chinese", "chi" },
		{ "Chuukese", "chk" },
		{ "Mari", "chm" },
		{ "Chinook jargon", "chn" },
		{ "Choctaw", "cho" },
		{ "Cherokee", "chr" },
		{ "Church Slavic", "chu" },
		{ "Chuvash", "chv" },
		{ "Cheyenne", "chy" },
		{ "Chamic languages", "cmc" },
		{ "Mandarin", "cmn" },
		{ "Coptic", "cop" },
		{ "Cornish", "cor" },
		{ "Corsican", "cos" },
		{ "Creoles and Pidgins, English-based (Other)", "cpe" },
		{ "Creoles and Pidgins, French-based (Other)", "cpf" },
		{ "Creoles and Pidgins, Portuguese-based (Other)", "cpp" },
		{ "Cree", "cre" },
		{ "Crimean Tatar", "crh" },
		{ "Creoles and Pidgins (Other)", "crp" },
		{ "Cushitic (Other)", "cus" },
		{ "Czech", "cze" },
		{ "Dakota", "dak" },
		{ "Danish", "dan" },
		{ "Dargwa", "dar" },
		{ "Dayak", "day" },
		{ "Delaware", "del" },
		{ "Dinka", "din" },
		{ "Maldivian", "div" },
		{ "Dogri", "doi" },
		{ "Dravidian (Other)", "dra" },
		{ "Duala", "dua" },
		{ "Dutch, Middle (ca. 1050-1350)", "dum" },
		{ "Dutch", "dut" },
		{ "Dyula", "dyu" },
		{ "Dzongkha", "dzo" },
		{ "Efik", "efi" },
		{ "Egyptian", "egy" },
		{ "Ekajuk", "eka" },
		{ "Elamite", "elx" },
		{ "English", "eng" },
		{ "English, Middle (1100-1500)", "enm" },
		{ "Esperanto", "epo" },
		{ "Eskimo languages", "esk" },
		{ "Esperanto", "esp" },
		{ "Estonian", "est" },
		{ "Ethiopic", "eth" },
		{ "Ewe", "ewe" },
		{ "Ewondo", "ewo" },
		{ "Fang", "fan" },
		{ "Faroese", "fao" },
		{ "Faroese", "far" },
		{ "Fanti", "fat" },
		{ "Fijian", "fij" },
		{ "Filipino", "fil" },
		{ "Finnish", "fin" },
		{ "Finno-Ugrian (Other)", "fiu" },
		{ "Fon", "fon" },
		{ "French", "fre" },
		{ "Frisian", "fri" },
		{ "French, Middle (ca. 1300-1600)", "frm" },
		{ "French, Old (ca. 842-1300)", "fro" },
		{ "East Frisian", "frs" },
		{ "Frisian", "fry" },
		{ "Fula", "ful" },
		{ "Friulian", "fur" },
		{ "Ga", "gaa" },
		{ "Scottish Gaelix", "gae" },
		{ "Galician", "gag" },
		{ "Oromo", "gal" },
		{ "Gayo", "gay" },
		{ "Gbaya", "gba" },
		{ "Germanic (Other)", "gem" },
		{ "Georgian", "geo" },
		{ "German", "ger" },
		{ "Ethiopic", "gez" },
		{ "Gilbertese", "gil" },
		{ "Scottish Gaelic", "gla" },
		{ "Irish", "gle" },
		{ "Galician ", "glg" },
		{ "Manx", "glv" },
		{ "German, Middle High (ca. 1050-1500)", "gmh" },
		{ "Old High German", "goh" },
		{ "Gondi", "gon" },
		{ "Gorontalo", "gor" },
		{ "Gothic", "got" },
		{ "Grebo", "grb" },
		{ "Ancient Greek", "grc" },
		{ "Greek", "gre" },
		{ "Guarani", "grn" },
		{ "Swiss German", "gsw" },
		{ "Guarani", "gua" },
		{ "Gujarati", "guj" },
		{ "Gullah", "gul" },
		{ "Haitian French Creole", "hat" },
		{ "Hausa", "hau" },
		{ "Hawaiian", "haw" },
		{ "Serbo-Croatian", "hbs" },
		{ "Hebrew", "heb" },
		{ "Herero", "her" },
		{ "Hiligaynon", "hil" },
		{ "Himachali", "him" },
		{ "Hindi", "hin" },
		{ "Hmong", "hmn" },
		{ "Hiri Motu", "hmo" },
		{ "Croatian", "hrv" },
		{ "Hungarian", "hun" },
		{ "Iban", "iba" },
		{ "Igbo", "ibo" },
		{ "Icelandic", "ice" },
		{ "Ido", "ido" },
		{ "Ijo", "ijo" },
		{ "Inuktitut", "iku" },
		{ "Iloko", "ilo" },
		{ "Interlingua (International Auxiliary Language Association)", "ina" },
		{ "Indic (Other)", "inc" },
		{ "Indonesian", "ind" },
		{ "Indo-European (Other)", "ine" },
		{ "Ingush", "inh" },
		{ "Interlingua (International Auxiliary Language Association)", "int" },
		{ "Inupiaq", "ipk" },
		{ "Iranian (Other)", "ira" },
		{ "Irish", "iri" },
		{ "Iroquoian (Other)", "iro" },
		{ "Italian", "ita" },
		{ "Javanese", "jav" },
		{ "Japanese", "jpn" },
		{ "Judeo-Persian", "jpr" },
		{ "Judeo-Arabic", "jrb" },
		{ "Kara-Kalpak", "kaa" },
		{ "Kabyle", "kab" },
		{ "Kachin", "kac" },
		{ "Kalatdlisut", "kal" },
		{ "Kamba", "kam" },
		{ "Kannada", "kan" },
		{ "Karen languages", "kar" },
		{ "Kashmiri", "kas" },
		{ "Kanuri", "kau" },
		{ "Kawi", "kaw" },
		{ "Kazakh", "kaz" },
		{ "Kabardian", "kbd" },
		{ "Khasi", "kha" },
		{ "Khoisan (Other)", "khi" },
		{ "Khmer", "khm" },
		{ "Khotanese", "kho" },
		{ "Kikuyu", "kik" },
		{ "Kinyarwanda", "kin" },
		{ "Kyrgyz", "kir" },
		{ "Kimbundu", "kmb" },
		{ "Konkani ", "kok" },
		{ "Komi", "kom" },
		{ "Kongo", "kon" },
		{ "Korean", "kor" },
		{ "Kusaie", "kos" },
		{ "Kpelle", "kpe" },
		{ "Karachay-Balkar", "krc" },
		{ "Karelian", "krl" },
		{ "Kru (Other)", "kro" },
		{ "Kurukh", "kru" },
		{ "Kuanyama", "kua" },
		{ "Kumyk", "kum" },
		{ "Kurdish", "kur" },
		{ "Ladino", "lad" },
		{ "Lahnda", "lah" },
		{ "Lamba (Zambia and Congo)", "lam" },
		{ "Occitan (post 1500)", "lan" },
		{ "Lao", "lao" },
		{ "Sami", "lap" },
		{ "Latin", "lat" },
		{ "Latvian", "lav" },
		{ "Lezgian", "lez" },
		{ "Lingala", "lin" },
		{ "Lithuanian", "lit" },
		{ "Mongo-Nkundu", "lol" },
		{ "Lozi", "loz" },
		{ "Luxembourgish", "ltz" },
		{ "Luba-Lulua", "lua" },
		{ "Luba-Katanga", "lub" },
		{ "Ganda", "lug" },
		{ "Lunda", "lun" },
		{ "Luo (Kenya and Tanzania)", "luo" },
		{ "Lushai", "lus" },
		{ "Macedonian", "mac" },
		{ "Madurese", "mad" },
		{ "Magahi", "mag" },
		{ "Marshallese", "mah" },
		{ "Maithili", "mai" },
		{ "Makasar", "mak" },
		{ "Malayalam", "mal" },
		{ "Mandingo", "man" },
		{ "Maori", "mao" },
		{ "Austronesian (Other)", "map" },
		{ "Marathi", "mar" },
		{ "Masai", "mas" },
		{ "Malay", "may" },
		{ "Moksha", "mdf" },
		{ "Mende", "men" },
		{ "Micmac", "mic" },
		{ "Minangkabau", "min" },
		{ "Miscellaneous languages", "mis" },
		{ "Mon-Khmer (Other)", "mkh" },
		{ "Malagasy", "mla" },
		{ "Malagasy", "mlg" },
		{ "Maltese", "mlt" },
		{ "Manchu", "mnc" },
		{ "Manipuri", "mni" },
		{ "Manobo languages", "mno" },
		{ "Mohawk", "moh" },
		{ "Moldavian", "mol" },
		{ "Mongolian", "mon" },
		{ "Moore", "mos" },
		{ "Multiple languages", "mul" },
		{ "Munda (Other)", "mun" },
		{ "Creek", "mus" },
		{ "Mirandese", "mwl" },
		{ "Marwari", "mwr" },
		{ "Mayan languages", "myn" },
		{ "Erzya", "myv" },
		{ "Nahuatl", "nah" },
		{ "North American Indian (Other)", "nai" },
		{ "Nauru", "nau" },
		{ "Navajo", "nav" },
		{ "Ndebele (South Africa)", "nbl" },
		{ "Ndebele (Zimbabwe)", "nde" },
		{ "Ndonga", "ndo" },
		{ "Low German", "nds" },
		{ "Nepali", "nep" },
		{ "Newari", "new" },
		{ "Niger-Kordofanian (Other)", "nic" },
		{ "Niuean", "niu" },
		{ "Norwegian (Nynorsk)", "nno" },
		{ "Norwegian (Bokmal)", "nob" },
		{ "Nogai", "nog" },
		{ "Old Norse", "non" },
		{ "Norwegian", "nor" },
		{ "Northern Sotho", "nso" },
		{ "Nubian languages", "nub" },
		{ "Nyanja", "nya" },
		{ "Nyankole", "nyn" },
		{ "Nyoro", "nyo" },
		{ "Nzima", "nzi" },
		{ "Occitan (post 1500)", "oci" },
		{ "Ojibwa", "oji" },
		{ "Oriya", "ori" },
		{ "Oromo", "orm" },
		{ "Osage", "osa" },
		{ "Ossetic", "oss" },
		{ "Turkish, Ottoman", "ota" },
		{ "Otomian languages", "oto" },
		{ "Papuan (Other)", "paa" },
		{ "Pangasinan", "pag" },
		{ "Pahlavi", "pal" },
		{ "Pampanga", "pam" },
		{ "Panjabi", "pan" },
		{ "Papiamento", "pap" },
		{ "Palauan", "pau" },
		{ "Old Persian (ca. 600-400 B.C.)", "peo" },
		{ "Persian", "per" },
		{ "Philippine (Other)", "phi" },
		{ "Pali", "pli" },
		{ "Polish", "pol" },
		{ "Ponape", "pon" },
		{ "Portuguese", "por" },
		{ "Prakrit languages", "pra" },
		{ "Provencal (to 1500)", "pro" },
		{ "Pushto", "pus" },
		{ "Quechua", "que" },
		{ "Rajasthani", "raj" },
		{ "Rarotongan", "rar" },
		{ "Romance (Other)", "roa" },
		{ "Raeto-Romance", "roh" },
		{ "Romani", "rom" },
		{ "Romanian", "rum" },
		{ "Rundi", "run" },
		{ "Russian", "rus" },
		{ "Sango (Ubangi Creole)", "sag" },
		{ "Yakut", "sah" },
		{ "South American Indian (Other)", "sai" },
		{ "Salishan languages", "sal" },
		{ "Samaritan Aramaic", "sam" },
		{ "Sanskrit", "san" },
		{ "Samoan", "sao" },
		{ "Sasak", "sas" },
		{ "Santali", "sat" },
		{ "Serbian", "scc" },
		{ "Scots", "sco" },
		{ "Croatian", "scr" },
		{ "Selkup", "sel" },
		{ "Semitic (Other)", "sem" },
		{ "Shan", "shn" },
		{ "Shona", "sho" },
		{ "Sidamo", "sid" },
		{ "Sinhalese", "sin" },
		{ "Siouan (Other)", "sio" },
		{ "Sino-Tibetan (Other)", "sit" },
		{ "Slavic (Other)", "sla" },
		{ "Slovak", "slo" },
		{ "Slovenian", "slv" },
		{ "Northern Sami", "sme" },
		{ "Sami", "smi" },
		{ "Samoan", "smo" },
		{ "Shona", "sna" },
		{ "Sindhi", "snd" },
		{ "Sinhalese", "snh" },
		{ "Soninke", "snk" },
		{ "Sogdian", "sog" },
		{ "Somali", "som" },
		{ "Songhai", "son" },
		{ "Sotho", "sot" },
		{ "Spanish", "spa" },
		{ "Sardinian", "srd" },
		{ "Sranan", "srn" },
		{ "Serbian", "srp" },
		{ "Serer", "srr" },
		{ "Nilo-Saharan (Other)", "ssa" },
		{ "Sotho", "sso" },
		{ "Swazi ", "ssw" },
		{ "Sukuma", "suk" },
		{ "Sundanese", "sun" },
		{ "Susu", "sus" },
		{ "Sumerian", "sux" },
		{ "Swahili", "swa" },
		{ "Swedish", "swe" },
		{ "Swazi", "swz" },
		{ "Syriac", "syc" },
		{ "Syriac, Modern", "syr" },
		{ "Tagalog", "tag" },
		{ "Tahitian", "tah" },
		{ "Tai", "tai" },
		{ "Tajik", "taj" },
		{ "Tamil", "tam" },
		{ "Tatar", "tar" },
		{ "Tatar", "tat" },
		{ "Telugu", "tel" },
		{ "Temne", "tem" },
		{ "Terena", "ter" },
		{ "Tetum", "tet" },
		{ "Tajik ", "tgk" },
		{ "Tagalog", "tgl" },
		{ "Thai", "tha" },
		{ "Tibetan", "tib" },
		{ "Tigre", "tig" },
		{ "Tigrinya", "tir" },
		{ "Tiv", "tiv" },
		{ "Tokelauan", "tkl" },
		{ "Tlingit", "tli" },
		{ "Tamashek", "tmh" },
		{ "Tonga (Nyasa)", "tog" },
		{ "Tongan", "ton" },
		{ "Tok Pisin", "tpi" },
		{ "Tsimshian", "tsi" },
		{ "Tswana", "tsn" },
		{ "Tsonga", "tso" },
		{ "Tswana", "tsw" },
		{ "Turkmen", "tuk" },
		{ "Tumbuka", "tum" },
		{ "Turkish", "tur" },
		{ "Altaic (Other)", "tut" },
		{ "Tuvaluan", "tvl" },
		{ "Twi", "twi" },
		{ "Tuvinian", "tyv" },
		{ "Udmurt ", "udm" },
		{ "Ugaritic", "uga" },
		{ "Uighur", "uig" },
		{ "Ukrainian", "ukr" },
		{ "Umbundu", "umb" },
		{ "Undetermined", "und" },
		{ "Urdu", "urd" },
		{ "Uzbek", "uzb" },
		{ "Vai", "vai" },
		{ "Venda", "ven" },
		{ "Vietnamese", "vie" },
		{ "Flemish", "vls" },
		{ "Wakashan languages", "wak" },
		{ "Wolayta", "wal" },
		{ "Waray", "war" },
		{ "Welsh", "wel" },
		{ "Sorbian (Other)", "wen" },
		{ "Wolof ", "wol" },
		{ "Oirat", "xal" },
		{ "Xhosa", "xho" },
		{ "Yao (Africa)", "yao" },
		{ "Yapese", "yap" },
		{ "Yiddish", "yid" },
		{ "Yoruba", "yor" },
		{ "Yupik languages", "ypk" },
		{ "Cantonese", "yue" },
		{ "Zapotec", "zap" },
		{ "Zande languages", "znd" },
		{ "Zulu", "zul" },
		{ "Zuni", "zun" },
		{ "Zaza", "zza" } 
	};
}